#!/usr/bin/env bash

if [[ $OSTYPE = darwin* ]] ; then
    if [ -d /usr/local/Cellar/ffmprovisr ] ; then
        ffmprovisr_path=$(find /usr/local/Cellar/ffmprovisr -iname 'index.html' | sort -M | tail -n1)
    fi
    if [ -z "${ffmprovisr_path}" ] ; then
        ffmprovisr_path='https://amiaopensource.github.io/ffmprovisr/'
    fi
    open "${ffmprovisr_path}"
fi
